apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: {{ .Values.app.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      {{- if .Values.istio.enabled }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.istio.injection | quote }}
        {{- with .Values.istio.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretName }}
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        command: ["/entrypoint.sh"]
        args: ["api"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PUBLIC_HOSTNAME
          value: {{ .Values.app.host | quote }}
        - name: PORT
          value: {{ .Values.app.port | quote }}
        - name: NODE_ENV
          value: {{ .Values.nodeEnvValue }}
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        # Should already be true but ensuring this nonetheless
        - name: NEXT_PUBLIC_SELF_HOSTED
          value: "true"
        - name: NEXT_PUBLIC_SELF_HOSTED_TLS
          value: {{ .Values.tls.enabled | quote }}
        envFrom:
        - secretRef:
            name: {{ .Values.secrets.postgres.name }}
        - secretRef:
            name: {{ .Values.secrets.clickhouse.name }}
        - secretRef:
            name: {{ .Values.secrets.jwt.name }}
        - secretRef:
            name: {{ .Values.secrets.kafka.name }}
        - secretRef:
            name: {{ .Values.secrets.objectStorage.name }}
        - secretRef:
            name: {{ .Values.secrets.prismaFieldEncryption.name }}
        ports:
        - containerPort: {{ .Values.app.port }}
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            path: '/'
            port: {{ .Values.app.port }}
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: '/'
            port: {{ .Values.app.port }}
        resources:
          requests:
            cpu: "1"
        lifecycle:
          preStop:
            exec:
              command: ["sleep","60"]
      terminationGracePeriodSeconds: 120
