apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    POSTGRES_USER: "gentrace"
    POSTGRES_PASSWORD: "gentrace123"
    POSTGRES_DB: "gentrace"
    DATABASE_URL: "postgresql://gentrace:gentrace123@postgres:5432/gentrace"
