services:
  app:
    platform: linux/amd64
    image: ${QUAY_IMAGE_URL_PREFIX:-quay.io}/gentrace/core:${GENTRACE_CORE_VERSION:-production}
    entrypoint: ["/bin/sh", "-c"]
    command: ["npm run self-hosted:migrate-and-seed && /entrypoint.sh app"]
    ports:
      - "3000:3000"
    environment:
      - OTEL_SDK_DISABLED=true
      - DATABASE_URL=${DATABASE_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_PROTOCOL=${CLICKHOUSE_PROTOCOL}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - KAFKA_BROKER=kafka
      - KAFKA_PORT=9092
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - STORAGE_REGION=${STORAGE_REGION}
      - STORAGE_FORCE_PATH_STYLE=${STORAGE_FORCE_PATH_STYLE}
      - PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      - PORT=${PORT}
      - NEXT_PUBLIC_SELF_HOSTED=${NEXT_PUBLIC_SELF_HOSTED}
      - NEXT_PUBLIC_SELF_HOSTED_TLS=${NEXT_PUBLIC_SELF_HOSTED_TLS}
      - JWT_SECRET=${JWT_SECRET}
      - PRISMA_FIELD_ENCRYPTION_KEY=${PRISMA_FIELD_ENCRYPTION_KEY}
      - WEBSOCKET_URL=${WEBSOCKET_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED="0"

      # Prisma environment variables
      - PRISMA_BINARIES_MIRROR=http://localhost:1
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
      - PRISMA_QUERY_ENGINE_BINARY=/app/node_modules/.prisma/client/query-engine-debian-openssl-3.0.x
      - PRISMA_QUERY_ENGINE_LIBRARY=/app/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node
      - PRISMA_SCHEMA_ENGINE_BINARY=/app/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x

      - NODE_ENV=${NODE_ENV}
      - ENVIRONMENT=${ENVIRONMENT}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      minio:
        condition: service_started

  # Note: Routing to websocket-server is not yet configured from the app container. This
  # service will not be accessible externally.
  websocket-server:
    platform: linux/amd64
    image: ${QUAY_IMAGE_URL_PREFIX:-quay.io}/gentrace/core:${GENTRACE_CORE_VERSION:-production}
    entrypoint: ["/entrypoint.sh"]
    command: ["websocket"]
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - OTEL_SDK_DISABLED=true
      - DATABASE_URL=${DATABASE_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_PROTOCOL=${CLICKHOUSE_PROTOCOL}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - KAFKA_BROKER=kafka
      - KAFKA_PORT=9092
      - PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      - PORT=3001
      - NEXT_PUBLIC_SELF_HOSTED=${NEXT_PUBLIC_SELF_HOSTED}
      - NEXT_PUBLIC_SELF_HOSTED_TLS=${NEXT_PUBLIC_SELF_HOSTED_TLS}
      - JWT_SECRET=${JWT_SECRET}
      - PRISMA_FIELD_ENCRYPTION_KEY=${PRISMA_FIELD_ENCRYPTION_KEY}
    depends_on:
      kafka:
        condition: service_healthy

  taskrunner:
    platform: linux/amd64
    image: ${QUAY_IMAGE_URL_PREFIX:-quay.io}/gentrace/core:${GENTRACE_CORE_VERSION:-production}
    entrypoint: ["/entrypoint.sh"]
    command: ["taskrunner"]
    environment:
      - OTEL_SDK_DISABLED=true
      - DATABASE_URL=${DATABASE_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_PROTOCOL=${CLICKHOUSE_PROTOCOL}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - KAFKA_BROKER=kafka
      - KAFKA_PORT=9092
      - PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      - NEXT_PUBLIC_SELF_HOSTED=${NEXT_PUBLIC_SELF_HOSTED}
      - NEXT_PUBLIC_SELF_HOSTED_TLS=${NEXT_PUBLIC_SELF_HOSTED_TLS}
      - JWT_SECRET=${JWT_SECRET}
      - PRISMA_FIELD_ENCRYPTION_KEY=${PRISMA_FIELD_ENCRYPTION_KEY}
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - STORAGE_REGION=${STORAGE_REGION}
      - STORAGE_FORCE_PATH_STYLE=${STORAGE_FORCE_PATH_STYLE}
    depends_on:
      kafka:
        condition: service_healthy

  taskscheduler:
    platform: linux/amd64
    image: ${QUAY_IMAGE_URL_PREFIX:-quay.io}/gentrace/core:${GENTRACE_CORE_VERSION:-production}
    entrypoint: ["/entrypoint.sh"]
    command: ["taskscheduler"]
    environment:
      - OTEL_SDK_DISABLED=true
      - DATABASE_URL=${DATABASE_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_PROTOCOL=${CLICKHOUSE_PROTOCOL}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - KAFKA_BROKER=kafka
      - KAFKA_PORT=9092
      - PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      - NEXT_PUBLIC_SELF_HOSTED=${NEXT_PUBLIC_SELF_HOSTED}
      - NEXT_PUBLIC_SELF_HOSTED_TLS=${NEXT_PUBLIC_SELF_HOSTED_TLS}
      - JWT_SECRET=${JWT_SECRET}
      - PRISMA_FIELD_ENCRYPTION_KEY=${PRISMA_FIELD_ENCRYPTION_KEY}
    depends_on:
      kafka:
        condition: service_healthy

  postgres:
    image: ${DOCKER_REGISTRY_URL_PREFIX:+$DOCKER_REGISTRY_URL_PREFIX/}postgres:15.3
    environment:
      # Change these values for production use
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gentrace"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: ${DOCKER_REGISTRY_URL_PREFIX:+$DOCKER_REGISTRY_URL_PREFIX/}confluentinc/cp-kafka:7.4.4
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "5Yr1SIgYQz-b-dgRabWx4g"
    healthcheck:
      test:
        ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: ${DOCKER_REGISTRY_URL_PREFIX:+$DOCKER_REGISTRY_URL_PREFIX/}provectuslabs/kafka-ui:latest
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - ./kafka-ui-config.yaml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - kafka

  kafka-connect:
    platform: linux/amd64
    image: ${QUAY_IMAGE_URL_PREFIX:-quay.io}/gentrace/kafka-connect-clickhouse
    ports:
      - "8083:8083"
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_PROTOCOL=${CLICKHOUSE_PROTOCOL}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CONNECT_BOOTSTRAP_SERVERS=${CONNECT_BOOTSTRAP_SERVERS}
      - CONNECT_KEY_CONVERTER=${CONNECT_KEY_CONVERTER}
      - CONNECT_VALUE_CONVERTER=${CONNECT_VALUE_CONVERTER}
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  minio:
    image: ${DOCKER_REGISTRY_URL_PREFIX:+$DOCKER_REGISTRY_URL_PREFIX/}minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # Change these values for production use
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  clickhouse:
    image: ${DOCKER_REGISTRY_URL_PREFIX:+$DOCKER_REGISTRY_URL_PREFIX/}clickhouse/clickhouse-server:24.8
    ports:
      - "8123:8123" # http port
      - "9100:9000" # native port
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  kafka_data:
  minio_data:
  clickhouse_data:
