apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskscheduler
  labels:
    app: {{ .Values.taskscheduler.name }}
spec:
  replicas: {{ .Values.taskscheduler.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: taskscheduler
  template:
    metadata:
      labels:
        app: {{ .Values.taskscheduler.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretName }}
      containers:
      - name: app
        image: "{{ .Values.taskscheduler.image }}:{{ .Values.taskscheduler.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PUBLIC_HOSTNAME
          value: {{ .Values.taskscheduler.host | quote }}
        - name: NODE_ENV
          value: {{ .Values.nodeEnvValue }}
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        # In case certain Next-specific code paths are hit in the taskrunner
        - name: NEXT_PUBLIC_SELF_HOSTED
          value: "true"
        - name: NEXT_PUBLIC_SELF_HOSTED_TLS
          value: {{ .Values.tls.enabled | quote }}
        envFrom:
          - secretRef:
              name: {{ .Values.secrets.postgres.name }}
          - secretRef:
              name: {{ .Values.secrets.clickhouse.name }}
          - secretRef:
              name: {{ .Values.secrets.jwt.name }}
          - secretRef:
              name: {{ .Values.secrets.kafka.name }}
          - secretRef:
              name: {{ .Values.secrets.objectStorage.name }}
          - secretRef:
              name: {{ .Values.secrets.prismaFieldEncryption.name }}
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          exec:
            command:
            - /bin/sh
            - -c
            - exit 0
        lifecycle:
          preStop:
            exec:
              # if SIGTERM triggers a quick exit; keep serving traffic instead
              command: ["sleep","60"]
      terminationGracePeriodSeconds: 120
