apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: gentrace-ingress-{{ .Values.environment }}
    annotations:
        ingress.kubernetes.io/enable-cors: "true"
        {{- if .Values.ingress.annotations }}
        {{- toYaml .Values.ingress.annotations | nindent 8 }}
        {{- end }}
spec:
    {{- if .Values.ingress.className }}
    ingressClassName: {{ .Values.ingress.className }}
    {{- end }}
    {{- if and .Values.tls.enabled .Values.tls.certificates }}
    tls:
    {{- range .Values.tls.certificates }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
    rules:
        - host: {{ .Values.app.host }}
          http:
              paths:
                  - path: /api
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: api-service
                            port:
                                number: {{ .Values.app.port }}
                  - path: /api/*
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: api-service
                            port:
                                number: {{ .Values.app.port }}
                  - path: /ws
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: websocket-service
                            port:
                                number: {{ .Values.websocketServer.port }}
                  - path: /*
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: app-service
                            port:
                                number: {{ .Values.app.port }}
