apiVersion: v1
kind: Service
metadata:
    name: websocket-service
spec:
    type: ClusterIP
    selector:
        app: websocket-server
    ports:
        - protocol: TCP
          port: {{ .Values.websocketServer.port }}
          targetPort: {{ .Values.websocketServer.port }}
    sessionAffinity: ClientIP
