apiVersion: v1
kind: Service
metadata:
    name: clickhouse
spec:
    ports:
        - name: http
          port: {{ .Values.clickhouse.httpPort }}
          targetPort: http
        - name: native
          port: {{ .Values.clickhouse.tcpPort }}
          targetPort: native
    selector:
        app: clickhouse
    clusterIP: None
