apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  user.xml: |
    <clickhouse>
      <users>
        <default>
          <access_management>1</access_management>
          <named_collection_control>1</named_collection_control>
          <show_named_collections>1</show_named_collections>
          <show_named_collections_secrets>1</show_named_collections_secrets>
          <!-- Enable the new query analyzer for recursive CTE support -->
          <enable_analyzer>1</enable_analyzer>
        </default>
      </users>
    </clickhouse>
