apiVersion: v1
kind: Service
metadata:
    name: kafka
spec:
    ports:
        - name: kafka
          port: {{ .Values.kafka.port }}
          targetPort: kafka
    selector:
        app: kafka
    clusterIP: None
