apiVersion: v1
kind: Service
metadata:
    name: kafka-connect
spec:
    ports:
        - name: connect-api
          port: {{ .Values.kafka.connect.port }}
          targetPort: connect-api
    selector:
        app: kafka-connect
    clusterIP: None 