apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
data:
  dynamic_config.yaml: |
    auth:
      type: DISABLED
    kafka:
      clusters:
        - bootstrapServers: kafka:{{ .Values.kafka.port }}
          name: self-hosted
          kafkaConnect:
            - address: http://kafka-connect:{{ .Values.kafka.connect.port }}
              name: clickhouse
          properties: {}
          readOnly: false
    rbac:
      roles: []
    webclient: {} 