{{- if and .Values.objectStorage.enabled .Values.objectStorage.useMinio }}
apiVersion: v1
kind: Service
metadata:
    name: minio
spec:
    type: ClusterIP
    ports:
        - name: api
          port: {{ .Values.objectStorage.minio.ports.api }}
          targetPort: api
        - name: console
          port: {{ .Values.objectStorage.minio.ports.console }}
          targetPort: console
    selector:
        app: minio
{{- end }} 