apiVersion: v1
kind: Service
metadata:
    name: postgres
spec:
    ports:
        - name: postgresql
          port: {{ .Values.postgres.port }}
          targetPort: postgresql
    selector:
        app: postgres
    clusterIP: None
