name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - ".github/workflows/docker-build.yml"

jobs:
  build-kafka-connect:
    name: Build Kafka Connect image
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-kafka-connect
          key: ${{ runner.os }}-buildx-kafka-connect-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-kafka-connect-

      - name: Build and push Kafka Connect image (AMD64)
        uses: docker/build-push-action@v4
        with:
          context: docker
          file: docker/Dockerfile.kafka-connect
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          tags: |
            quay.io/gentrace/kafka-connect-clickhouse:latest
            quay.io/gentrace/kafka-connect-clickhouse:v1.0.0-amd64
          cache-from: type=local,src=/tmp/.buildx-cache-kafka-connect
          cache-to: type=local,dest=/tmp/.buildx-cache-kafka-connect-new

      - name: Build and push Kafka Connect image (ARM64)
        uses: docker/build-push-action@v4
        with:
          context: docker
          file: docker/Dockerfile.kafka-connect
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: true
          tags: |
            quay.io/gentrace/kafka-connect-clickhouse:v1.0.0-arm64
          cache-from: type=local,src=/tmp/.buildx-cache-kafka-connect
          cache-to: type=local,dest=/tmp/.buildx-cache-kafka-connect-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-kafka-connect
          mv /tmp/.buildx-cache-kafka-connect-new /tmp/.buildx-cache-kafka-connect
