name: Docker Compose Test

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-compose-test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-compose-test.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test Docker Compose Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate .env file with secrets
        run: |
          echo "JWT_SECRET=$(openssl rand -hex 32)" > docker/.env
          echo "PRISMA_FIELD_ENCRYPTION_KEY=$(openssl rand -hex 32)" >> docker/.env
          # Add default database credentials for testing
          echo "POSTGRES_USER=postgres" >> docker/.env
          echo "POSTGRES_PASSWORD=postgres" >> docker/.env
          echo "POSTGRES_DB=postgres" >> docker/.env
          # Add default DATABASE_URL for services
          echo "DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres" >> docker/.env

      - name: Start services with Docker Compose
        run: |
          cd docker
          # Start services with explicit env-file and allow failures to continue for diagnostics
          docker compose --env-file .env up -d || true

      - name: Wait for services to be healthy
        run: |
          cd docker
          echo "Waiting for services to be healthy..."
          for i in {1..30}; do
            if docker compose ps | grep -q "healthy"; then
              echo "Services are healthy!"
              break
            fi
            echo "Services not healthy yet, retrying..."
            sleep 2
          done

      - name: Check logs for errors
        run: |
          cd docker
          # Dump Postgres container logs via compose to capture startup errors
          POSTGRES_ID=$(docker compose ps -q postgres) && echo "Postgres container ID: $POSTGRES_ID"
          if [ -n "$POSTGRES_ID" ]; then
            echo "=== Postgres Logs ==="
            docker logs "$POSTGRES_ID"
          else
            echo "No Postgres container found."
          fi
          # Print full docker-compose logs
          echo "=== Full Docker Compose Logs ==="
          docker compose logs --no-color
          # Show service status
          echo "=== Service Status ==="
          docker compose ps
          # Fail if any errors in logs
          if docker compose logs --no-color | grep -i "error"; then
            echo "Errors found in logs."
            exit 1
          else
            echo "No errors found in logs."
          fi

      - name: Test API health endpoint
        run: |
          cd docker
          echo "Testing API health endpoint..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/api/health | grep -q "ok"; then
              echo "API health is ok!"
              break
            fi
            echo "API not ready, retrying..."
            sleep 2
          done

      - name: Test login endpoint
        run: |
          cd docker
          echo "Testing login endpoint..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:3000/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{"email":"test@gentrace.ai","password":"TestPassword123"}')
          if [ "$STATUS" -ne 200 ]; then
            echo "Login test failed with status $STATUS"
            exit 1
          fi
          echo "Login test passed!"
