name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          release-type: helm

      # Helm publish steps - only run if a release was created
      - name: Checkout for Helm
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.HELM_GITHUB_TOKEN }}

      - name: Configure Git
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Helm
        if: ${{ steps.release.outputs.release_created }}
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Package Helm Chart
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir -p .cr-release-packages
          helm package kubernetes/helm-chart -d .cr-release-packages

      - name: Checkout gh-pages
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git checkout gh-pages
          cp .cr-release-packages/* .
          rm -rf .cr-release-packages

      - name: Generate Helm Repository Index
        if: ${{ steps.release.outputs.release_created }}
        run: |
          helm repo index .

      - name: Commit and Push Changes
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git add index.yaml *.tgz
          git commit -m "chore: update helm repository"
          git push origin gh-pages
