name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # Config file path relative to root
          config-file: release-please-config.json
          # Optional: customize manifest file path
          manifest-file: .release-please-manifest.json
